require('nvim-tree').setup({
  auto_reload_on_write = true,
  create_in_closed_folder = false,
  disable_netrw = false,
  hijack_cursor = false,
  hijack_netrw = true,
  hijack_unnamed_buffer_when_opening = false,
  ignore_buffer_on_setup = false,
  open_on_setup = false,
  open_on_setup_file = false,
  open_on_tab = false,
  ignore_buf_on_tab_change = {},
  sort_by = 'name',
  root_dirs = {},
  prefer_startup_root = false,
  sync_root_with_cwd = false,
  reload_on_bufenter = false,
  respect_buf_cwd = false,
  on_attach = 'disable', -- function(bufnr). If nil, will use the deprecated mapping strategy
  remove_keymaps = false, -- boolean (disable totally or not) or list of key (lhs)
  view = {
    adaptive_size = true,
    centralize_selection = false,
    hide_root_folder = false,
    side = 'left',
    preserve_window_proportions = true,
    number = false,
    relativenumber = false,
    signcolumn = 'yes',
  },
  renderer = {
    add_trailing = true,
    highlight_git = true,
    root_folder_modifier = ':~',
    indent_markers = {
      enable = true,
      inline_arrows = true,
    },
    icons = {
      webdev_colors = true,
      git_placement = 'after',
      padding = ' ',
      symlink_arrow = icon('arrow-right'),
      show = {
        file = true,
        folder = true,
        folder_arrow = true,
        git = true,
      },
      glyphs = {
        default = icon('file'),
        symlink = icon('file-symlink-file'),
        bookmark = icon('bookmark'),
        folder = {
          arrow_closed = icon('triangle-right'),
          arrow_open = icon('triangle-down'),
          default = '',
          open = '',
          empty = icon('file-directory'),
          empty_open = '',
          symlink = icon('file-submodule'),
          symlink_open = icon('file-submodule'),
        },
        git = {
          unstaged = icon('x'),
          staged = icon('check'),
          unmerged = icon('git-merge'),
          renamed = icon('diff-renamed'),
          untracked = icon('star'),
          deleted = icon('diff-removed'),
          ignored = icon('diff-ignored'),
        },
      },
    },
    special_files = { 'Cargo.toml', 'Makefile', 'README.md', 'readme.md' },
    symlink_destination = true,
  },
  hijack_directories = {
    enable = true,
    auto_open = true,
  },
  update_focused_file = {
    enable = true,
    update_root = true,
    ignore_list = {},
  },
  ignore_ft_on_setup = {},
  system_open = {
    cmd = '',
    args = {},
  },
  diagnostics = {
    enable = true,
    show_on_dirs = false,
    debounce_delay = 50,
    icons = {
      hint = icon('light-bulb'),
      info = icon('info'),
      warning = icon('alert'),
      error = icon('x-circle'),
    },
  },
  filters = {
    dotfiles = true,
    custom = {},
    exclude = {},
  },
  filesystem_watchers = {
    enable = true,
    debounce_delay = 50,
  },
  git = {
    enable = true,
    ignore = true,
    show_on_dirs = false,
    timeout = 400,
  },
  actions = {
    use_system_clipboard = true,
    change_dir = {
      enable = true,
      global = false,
      restrict_above_cwd = false,
    },
    expand_all = {
      max_folder_discovery = 300,
      exclude = {},
    },
    file_popup = {
      open_win_config = {
        col = 1,
        row = 1,
        relative = 'cursor',
        border = 'shadow',
        style = 'minimal',
      },
    },
    open_file = {
      quit_on_open = true,
      resize_window = true,
      window_picker = {
        enable = true,
        chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890',
        exclude = {
          filetype = {
            'notify',
            'packer',
            'qf',
            'diff',
            'fugitive',
            'fugitiveblame',
          },
          buftype = { 'nofile', 'terminal', 'help' },
        },
      },
    },
    remove_file = {
      close_window = true,
    },
  },
  trash = {
    cmd = 'gio trash',
    require_confirm = true,
  },
  live_filter = {
    prefix = icon('filter') .. ' ',
    always_show_folders = false,
  },
  log = {
    enable = false,
    truncate = false,
    types = {
      all = false,
      config = false,
      copy_paste = false,
      dev = false,
      diagnostics = false,
      git = false,
      profile = false,
      watcher = false,
    },
  },
})
