local settings = {
    header = {
        type = "text",
        align = "center",
        fold_section = false,
        title = "Header",
        margin = 5,
        content = require("startup.headers").hydra_header,
        highlight = "Statement",
        default_color = "",
        oldfiles_amount = 0,
    },
    header_2 = {
        type = "text",
        oldfiles_directory = false,
        align = "center",
        fold_section = false,
        title = "Quote",
        margin = 5,
        content = require("startup.functions").quote(),
        highlight = "Boolean",
        default_color = "",
        oldfiles_amount = 0,
    },
    body = {
        type = "mapping",
        align = "center",
        fold_section = true,
        title = "Basic commands",
        margin = 15,
        content = {
            { "New File", "lua require'startup'.new_file()", "<leader>nf" },
            { "File browser", "Telescope file_browser", "<leader>b" },
            { "Find File", "Telescope find_files", "<leader>tf" },
            { "Find Word", "Telescope live_grep", "<leader>tw" },
            { "Recent Files", "Telescope oldfiles", "<leader>tr" },
            { "Projects", "Telescope project", "<leader>tp" },
            { "Keybindings", "WhichKey", "<leader>k" },
        },
        highlight = "",
        default_color = "",
        oldfiles_amount = 0,
    },
    footer = {
        type = "mapping",
        align = "center",
        fold_section = false,
        title = "Footer",
        margin = 5,
        content = { { "Update plugins", "PackerUpdate", 'by Packer' } },
        highlight = "TSComment",
        default_color = "",
        oldfiles_amount = 0,
    },
    footer_2 = {
        type = "text",
        content = require("startup.functions").packer_plugins(),
        oldfiles_directory = false,
        align = "center",
        fold_section = false,
        title = "",
        margin = 5,
        highlight = "TSComment",
        default_color = "#FFFFFF",
        oldfiles_amount = 10,
    },
    options = {
        after = function()
            require("startup.utils").oldfiles_mappings()
        end,
        mapping_keys = true,
        cursor_column = 0.5,
        empty_lines_between_mappings = true,
        disable_statuslines = true,
        paddings = { 4, 4, 3, 3, 1 },
    },
    colors = {
        background = "#1f2227",
        folded_section = "#56b6c2",
    },
    parts = {
        "header",
        "header_2",
        "body",
        "footer_2",
        "footer",
    },
}
return settings
