local require = require('neviraide.ui.neviraide-ui.utils.lazy')

local Api = require('neviraide.ui.neviraide-ui.api')
local Config = require('neviraide.ui.neviraide-ui.config')

local M = {}

M.api = Api

---Setup configuration
---@param opts? NeviraideUIConfig
function M.setup(opts)
  local function load()
    vim.opt.statusline =
      '%!v:lua.require("neviraide.ui.neviraide-ui.statusline").run()'
    require('neviraide.ui.neviraide-ui.utils').try(function()
      require('neviraide.ui.neviraide-ui.config').setup(opts)
      require('neviraide.ui.neviraide-ui.commands').setup()
      require('neviraide.ui.neviraide-ui.message.router').setup()
      M.enable()
    end)
  end

  if vim.v.vim_did_enter == 0 then
    -- Schedule loading after VimEnter. Get the UI up and running first.
    vim.api.nvim_create_autocmd('VimEnter', {
      once = true,
      callback = load,
    })
  else
    -- Schedule on the event loop
    vim.schedule(load)
  end
end

function M.disable()
  Config._running = false
  require('neviraide.ui.neviraide-ui.source.notify').disable()
  require('neviraide.ui.neviraide-ui.message.router').disable()
  require('neviraide.ui.neviraide-ui.ui').disable()
  require('neviraide.ui.neviraide-ui.utils.hacks').disable()
end

M.deactivate = M.disable

function M.cmd(name) require('neviraide.ui.neviraide-ui.commands').cmd(name) end

function M.enable()
  Config._running = true
  require('neviraide.ui.neviraide-ui.source.notify').enable()

  local hyprTheme =
    require('neviraide.ui.neviraide-ui.hyprland.utils').get_theme_from_hypr()
  require('neviraide.ui.neviraide-ui.utils.change_theme').change_theme(
    hyprTheme
  )

  require('neviraide.ui.neviraide-ui.utils.hacks').enable()
  require('neviraide.ui.neviraide-ui.ui').enable()
  require('neviraide.ui.neviraide-ui.message.router').enable()
end

-- Redirect any messages generated by a command or function
---@param cmd string|fun() command or function to execute
---@param routes? NeviraideUIRouteConfig[] custom routes. Defaults to `config.redirect`
function M.redirect(cmd, routes)
  return require('neviraide.ui.neviraide-ui.message.router').redirect(
    cmd,
    routes
  )
end

---@param msg string
---@param level number|string
---@param opts? table<string, any>
function M.notify(msg, level, opts)
  -- opts = vim.tbl_deep_extend('force', opts, {
  --   minimum_width = 10,
  -- })
  local mw = { minimum_width = 10 }
  if type(opts) == 'table' then table.insert(opts, mw) end
  return require('neviraide.ui.neviraide-ui.source.notify').notify(
    msg,
    level,
    opts
  )
end

return M
