local M = {}

M.base_30 = {
  accent = '#3d59a1',
  white = '#c0caf5',
  darker_black = '#16161e',
  black = '#1a1b26', --  nvim bg
  black2 = '#1f2336',
  one_bg2 = '#414868',
  one_bg3 = '#353b45',
  light_grey = '#545c7e',
  baby_pink = '#DE8C92',
  pink = '#ff75a0',
  vibrant_green = '#73daca',
  nord_blue = '#80a8fd',
  grey = '#403D4E',
  grey_fg2 = '#403D4E',
  one_bg = '#241B2F',
  grey_fg = '#495495',
  dark_purple = '#9d7cd8',
  teal = '#1abc9c',
  statusline_bg = '#1d1e29',
  lightbg = '#32333e',
  pmenu_bg = '#2C2540',
  folder_bg = '#7aa2f7',

  green = '#72f1b8',
  blue = '#03edf9',
  red = '#fe4450',
  line = '#241B2F', -- for lines like vertsplit
  purple = '#ff7edb',
  yellow = '#fede5d',
  sun = '#f3e70f',
  orange = '#ff8b39',
  cyan = '#03edf9',
}

M.base_16 = {
  base00 = '#262335',
  base01 = '#2C2540',
  base02 = '#3E3B4B',
  base03 = '#444b6a',
  base04 = '#787c99',
  base05 = '#D884C7',
  base06 = '#cbccd1',
  base07 = '#d5d6db',
  base08 = '#40ffff',
  base09 = '#E55A5E',
  base0A = '#0db9d7',
  base0B = M.base_30.orange,
  base0C = '#b4f9f8',
  base0D = '#40ffff',
  base0E = M.base_30.yellow,
  base0F = '#f7768e',
}

M.polish_hl = {
  Normal = { fg = '#ecebed', bg = '#262335' },
  ColorColumn = { fg = 'NONE', bg = '#2C2540' },
  CursorColumn = { fg = 'NONE', bg = '#2C2540' },
  CursorLine = { fg = 'NONE', bg = '#2C2540' },
  CursorLineNr = { fg = '#D4D3D7', bg = '#2C2540' },
  DiffAdd = { fg = 'NONE', bg = '#90DEB6' },
  DiffChange = { fg = 'NONE', bg = '#D884C7' },
  DiffDelete = { fg = 'Black', bg = '#EB8F82', bold = true },
  DiffText = { fg = 'NONE', bg = 'Red', bold = true },
  FoldColumn = { fg = '#495495', bg = '#2C2540' },
  Folded = { fg = '#495495', bg = '#2C2540' },
  LineNr = { fg = '#888690', bg = 'NONE' },
  NonText = { fg = '#495495', bg = 'NONE' },
  Pmenu = { fg = '#ECEBED', bg = '#2C2540' },
  PmenuSbar = { fg = 'NONE', bg = '#3E3B4B' },
  PmenuSel = { fg = '#ECEBED', bg = '#495495' },
  PmenuThumb = { fg = 'NONE', bg = '#ECEBED' },
  Search = { fg = 'Black', bg = '#FEDE5D' },
  SignColumn = { fg = '#888690', bg = 'NONE' },
  SignColumn = { fg = '#ECEBED', bg = 'NONE' },
  SpecialKey = { fg = '#ECEBED', bg = '#2C2540' },
  StatusLine = { fg = '#ECEBED', bg = '#2C2540' },
  StatusLineNC = { fg = '#ECEBED', bg = '#2C2540' },
  TabLine = { fg = '#495495', bg = '#2C2540' },
  TabLineFill = { fg = 'NONE', bg = '#2C2540' },
  TabLineSel = { fg = '#EB8F82', bg = '#2C2540' },
  Title = { fg = '#D884C7', bg = 'NONE' },
  Todo = { fg = 'Black', bg = '#FEDE5D' },
  VertSplit = { fg = '#2C2540', bg = '#495495' },
  Visual = { fg = 'NONE', bg = '#3E3B4B' },
  VisualNOS = { fg = 'NONE', bg = 'NONE' },
  WildMenu = { fg = 'Black', bg = '#FEDE5D' },
  Comment = { fg = '#495495', bg = 'NONE' },
  Constant = { fg = '#E55A5E', bg = 'NONE' },
  Error = { fg = '#ECEBED', bg = 'Red' },
  Identifier = { fg = '#40ffff', bg = 'NONE' },
  Ignore = { fg = 'Black', bg = 'NONE' },
  Include = { fg = '#90DEB6', bg = 'NONE' },
  PreProc = { fg = '#FEDE5D', bg = 'NONE' },
  Special = { fg = '#EA9652', bg = 'NONE' },
  Statement = { fg = '#FEDE5D', bg = 'NONE' },
  String = { fg = '#EA9652', bg = 'NONE' },
  Type = { fg = '#E55A5E' },
  Underlined = { fg = '#40ffff', bg = 'NONE' },
  EndOfBuffer = { link = 'NonText' },
  QuickFixLine = { link = 'Search' },
  Boolean = { link = 'Constant' },
  Character = { link = 'Constant' },
  Conditional = { link = 'Statement' },
  Define = { link = 'PreProc' },
  Debug = { link = 'Special' },
  Delimiter = { link = 'Special' },
  Exception = { link = 'Statement' },
  Float = { link = 'Number' },
  Function = { link = 'Identifier' },
  Keyword = { link = 'Statement' },
  Label = { link = 'Statement' },
  Macro = { link = 'PreProc' },
  Number = { link = 'Constant' },
  Operator = { link = 'Statement' },
  PreCondit = { link = 'PreProc' },
  Repeat = { link = 'Statement' },
  SpecialChar = { link = 'Special' },
  SpecialComment = { link = 'Special' },
  StorageClass = { link = 'Type' },
  Structure = { link = 'Type' },
  Tag = { link = 'Special' },
  Typedef = { link = 'Type' },
  lCursor = { link = 'Cursor' },
  typescriptFlowMaybe = { link = 'Normal' },
  typescriptFlowObject = { link = 'Normal' },
  typescriptFlowType = { link = 'PreProc' },
  typescriptClassDefinition = { link = 'Normal' },
  typescriptClassFuncName = { link = 'Title' },
  typescriptImport = { link = 'Include' },
  typescriptExport = { link = 'Include' },
  typescriptFrom = { link = 'PreProc' },
  typescriptFuncName = { link = 'Identifier' },
  typescriptFutureKeys = { link = 'Statement' },
  typescriptFuncCall = { link = 'Identifier' },
  typescriptModuleKeywords = { link = 'Statement' },
  typescriptModuleOperators = { link = 'Statement' },
  typescriptNull = { link = 'Constant' },
  typescriptObjectFuncName = { link = 'Identifier' },
  typescriptObjectKey = { link = 'Title' },
  typescriptSuper = { link = 'Statement' },
  typescriptTemplateBraces = { link = 'Special' },
  typescriptUndefined = { link = 'Constant' },
  typescriptFunction = { link = 'PreProc' },
  typescriptThis = { link = 'Constant' },
  typescriptStorageClass = { link = 'PreProc' },
  typescriptVariableDef = { link = 'Title' },
  typescriptAsyncKeyword = { link = 'Title' },
  typescriptFuncArgs = { link = 'Title' },
  typescriptArrowFuncArgs = { link = 'Title' },
  typescriptArrowFunction = { link = 'PreProc' },
  typescriptObjectShorthandProp = { link = 'Title' },
  typescriptGlobalObjects = { link = 'Constant' },
  typescriptModuleKeyword = { link = 'Title' },
  typescriptClassStringKey = { link = 'Title' },
  typescriptObjectKeyComputed = { link = 'Title' },
  typescriptObjectValue = { link = 'Title' },
  typescriptBlockLabel = { link = 'Title' },
  typescriptBlockLabelKey = { link = 'Title' },
  rubyClass = { link = 'PreProc' },
  rubyConstant = { link = 'Constant' },
  rubyInstanceVariable = { link = 'Title' },
  rubyInterpolationDelimiter = { link = 'Identifier' },
  rubyModule = { link = 'Statement' },
  rubyFunction = { link = 'Identifier' },
  rubyInclude = { link = 'Include' },
  markdownBold = { link = 'Special' },
  markdownCode = { link = 'String' },
  markdownCodeDelimiter = { link = 'String' },
  markdownHeadingDelimiter = { link = 'Comment' },
  markdownRule = { link = 'Comment' },
}

M.type = 'dark'

return M
